version: "3.3"

services:
  ner-api:
    image: "gicp:service-ner"
    build: ./api_ner
    restart: unless-stopped
    environment:
      API_KEY: ${NER_SERVICE_API_KEY}
      MAX_DATA_BY_REQUEST: ${NER_SERVICE_MAX_DATA_BY_REQUEST}
      MAX_WORKERS: ${NER_SERVICE_MAX_WORKERS:-1}
    labels:
      - traefik.enable=true
      - traefik.http.routers.api_ner.rule=Host(`ner.localhost`)
      - traefik.http.routers.api_ner.entrypoints=web
      #- traefik.http.services.api_ner.loadbalancer.server.port=23540
    networks:
      ner_service_net:
        aliases:
          - api-ner